### ISSUE TITLE
Make request interval adaptable

### ISSUE THREAD

**Issue by Thoralf-M** [machineeconomy/iota-payment#18]
Now we just send a request every 9 seconds if there is an open payment/payout, if it doesn't make a big difference if it takes more seconds (i.e. already 40 minutes past, but it could also take 2 hours) we shouldn't send a request to get the balance every 9 seconds, but slower

For payouts it could also made payment dependent, if we don't have enough iotas we have to wait for a payment to get new iotas, so we could wait until we received a new payment before we try it again

**Comment by huhn511** [comment]
I think for the most use cases, the payment will arrive a few minutes after the creation. We could decrease the request interval for each payment and delete it after X minutes/hours. 
Example:

Payment created -> check every 9 seconds 
After 9 Minutes no payment -> check every 9 minutes
After 90 minutes -> check every 90 minutes
After 9 days -> delete the payment

What do you think?

**Comment by Thoralf-M** [comment]
#23
