### ISSUE TITLE
observe first payment (with fresh seed and db)

### ISSUE THREAD

**Issue by huhn511** [machineeconomy/iota-payment#34]
There was a bug - the first payment switched the state without any incoming transaction. 

Watch this behavior and fix it!

**Comment by Thoralf-M** [comment]
Did you have already a balance on the first address? We should increase the startindex and mention that the balance should be sent only to the first address of the seed

**Comment by Thoralf-M** [comment]
#39

**Comment by huhn511** [comment]
Works fine now 👍
