### ISSUE TITLE
Evaluate ZMQ listener

### ISSUE THREAD

**Issue by huhn511** [machineeconomy/iota-payment#6]
Evaluate the ZMQ listener to track and report incoming payments.

Is the workload too heavy? (Too many "garbage" transactions)
We only get the incoming transactions, it's not confirmed yet.

**Comment by Thoralf-M** [comment]
> We only get the incoming transactions, it's not confirmed yet.

We could also just listen for single addresses and 'sn' for confirmed txs

**Comment by huhn511** [comment]
Done by @Thoralf-M 
https://github.com/machineeconomy/iota-payment/commit/f361bf35c60edc3f241079737db09662eec686a5
